
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Tasks@2024
      MYSQL_DATABASE: tasks

    volumes:
      - tasks_mariadb_data:/var/lib/mysql

volumes:
  tasks_mariadb_data:
